# Generated by Django 6.0.6 on 2026-06-29 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradorGaleria',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=255)),
                ('rol_interno', models.CharField(default='Curador', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=255)),
                ('estilo_artistico', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=255)),
                ('preferencias_arte', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObraArte',
            fields=[
                ('id_obra', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('tecnica', models.CharField(max_length=100)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('dimensiones', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disponibilidad', models.CharField(choices=[('Disponible', 'Disponible'), ('Reservada', 'Reservada'), ('Vendida', 'Vendida')], default='Disponible', max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('artista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='usuarios.artista')),
            ],
        ),
    ]
